const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const MAIN_SCREEN_BEST_POPULAR_MOVIE_AND_SERIALS =
    "BEST POPULAR MOVIE AND SERIALS";
const SHOW_CASES_TITLE = "SHOW CASES";
const SHOW_CASES_SEE_MORE = "MORE SHOWCASES";
const BEST_ACTORS_TITLE = "BEST ACTORS";
const BEST_ACTORS_SEE_MORE = "MORE ACTORS";
const MAIN_SCREEN_SEE_MORE = "SEE MORE";
const MAIN_SCREEN_CHECK_MOVIE_SHOW_TIME = "Check Movie \nShow Time";
const MOVIE_DETAIL_SCREEN_ACTOR_TITLE = "ACTORS";
const MOVIE_DETAIL_SCREEN_CREATOR_TITLE = "CREATORS";
const MOVIE_DETAIL_SCREEN_CREATORS_SEEMORE = "MORE CREATORS";
const MOVIE_DETAIL_SCREEN_STORYLINE = "STORYLINE";
